bump version of HdrHistogram to fix ArrayIndexOutOfBoundsException
Bumping Version 2.1.12 includes fix for https://github.com/HdrHistogram/HdrHistogram/issues/156
This should solve the exception we are seeing:
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: value outside of histogram covered range. Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1332405 out of bounds for length 1310720

Signed-off-by: Vanessa Busch <vbusch@redhat.com>